// Code generated by protoc-gen-go. DO NOT EDIT.
// source: luna.proto

package lunapb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The top-level message sent by the client for the `Version` method.
type VersionRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionRequest) Reset()         { *m = VersionRequest{} }
func (m *VersionRequest) String() string { return proto.CompactTextString(m) }
func (*VersionRequest) ProtoMessage()    {}
func (*VersionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ac2cc9edf97f76d, []int{0}
}

func (m *VersionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionRequest.Unmarshal(m, b)
}
func (m *VersionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionRequest.Marshal(b, m, deterministic)
}
func (m *VersionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionRequest.Merge(m, src)
}
func (m *VersionRequest) XXX_Size() int {
	return xxx_messageInfo_VersionRequest.Size(m)
}
func (m *VersionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VersionRequest proto.InternalMessageInfo

// The top-level message sent by the client for the `ListVoices` method.
type ListVoicesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListVoicesRequest) Reset()         { *m = ListVoicesRequest{} }
func (m *ListVoicesRequest) String() string { return proto.CompactTextString(m) }
func (*ListVoicesRequest) ProtoMessage()    {}
func (*ListVoicesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ac2cc9edf97f76d, []int{1}
}

func (m *ListVoicesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListVoicesRequest.Unmarshal(m, b)
}
func (m *ListVoicesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListVoicesRequest.Marshal(b, m, deterministic)
}
func (m *ListVoicesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListVoicesRequest.Merge(m, src)
}
func (m *ListVoicesRequest) XXX_Size() int {
	return xxx_messageInfo_ListVoicesRequest.Size(m)
}
func (m *ListVoicesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListVoicesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListVoicesRequest proto.InternalMessageInfo

// The top-level message sent by the client for the `Synthesize` and
// `SynthesizeStream` methods.
type SynthesizeRequest struct {
	// Provides configuration for the text-to-speech engine.
	Config *SynthesizerConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	// The text to generate speech for.
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SynthesizeRequest) Reset()         { *m = SynthesizeRequest{} }
func (m *SynthesizeRequest) String() string { return proto.CompactTextString(m) }
func (*SynthesizeRequest) ProtoMessage()    {}
func (*SynthesizeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ac2cc9edf97f76d, []int{2}
}

func (m *SynthesizeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SynthesizeRequest.Unmarshal(m, b)
}
func (m *SynthesizeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SynthesizeRequest.Marshal(b, m, deterministic)
}
func (m *SynthesizeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SynthesizeRequest.Merge(m, src)
}
func (m *SynthesizeRequest) XXX_Size() int {
	return xxx_messageInfo_SynthesizeRequest.Size(m)
}
func (m *SynthesizeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SynthesizeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SynthesizeRequest proto.InternalMessageInfo

func (m *SynthesizeRequest) GetConfig() *SynthesizerConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *SynthesizeRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

// Configuration for setting up the text-to-speech engine.
type SynthesizerConfig struct {
	VoiceId              string   `protobuf:"bytes,1,opt,name=voice_id,json=voiceId,proto3" json:"voice_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SynthesizerConfig) Reset()         { *m = SynthesizerConfig{} }
func (m *SynthesizerConfig) String() string { return proto.CompactTextString(m) }
func (*SynthesizerConfig) ProtoMessage()    {}
func (*SynthesizerConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ac2cc9edf97f76d, []int{3}
}

func (m *SynthesizerConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SynthesizerConfig.Unmarshal(m, b)
}
func (m *SynthesizerConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SynthesizerConfig.Marshal(b, m, deterministic)
}
func (m *SynthesizerConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SynthesizerConfig.Merge(m, src)
}
func (m *SynthesizerConfig) XXX_Size() int {
	return xxx_messageInfo_SynthesizerConfig.Size(m)
}
func (m *SynthesizerConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_SynthesizerConfig.DiscardUnknown(m)
}

var xxx_messageInfo_SynthesizerConfig proto.InternalMessageInfo

func (m *SynthesizerConfig) GetVoiceId() string {
	if m != nil {
		return m.VoiceId
	}
	return ""
}

// The message sent by the server for the `Version` method.
type VersionResponse struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionResponse) Reset()         { *m = VersionResponse{} }
func (m *VersionResponse) String() string { return proto.CompactTextString(m) }
func (*VersionResponse) ProtoMessage()    {}
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ac2cc9edf97f76d, []int{4}
}

func (m *VersionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionResponse.Unmarshal(m, b)
}
func (m *VersionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionResponse.Marshal(b, m, deterministic)
}
func (m *VersionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionResponse.Merge(m, src)
}
func (m *VersionResponse) XXX_Size() int {
	return xxx_messageInfo_VersionResponse.Size(m)
}
func (m *VersionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VersionResponse proto.InternalMessageInfo

func (m *VersionResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

// The message sent by the server for the `ListVoices` method.
type ListVoicesResponse struct {
	// List of voices available for use that match the request.
	Voices               []*Voice `protobuf:"bytes,1,rep,name=voices,proto3" json:"voices,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListVoicesResponse) Reset()         { *m = ListVoicesResponse{} }
func (m *ListVoicesResponse) String() string { return proto.CompactTextString(m) }
func (*ListVoicesResponse) ProtoMessage()    {}
func (*ListVoicesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ac2cc9edf97f76d, []int{5}
}

func (m *ListVoicesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListVoicesResponse.Unmarshal(m, b)
}
func (m *ListVoicesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListVoicesResponse.Marshal(b, m, deterministic)
}
func (m *ListVoicesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListVoicesResponse.Merge(m, src)
}
func (m *ListVoicesResponse) XXX_Size() int {
	return xxx_messageInfo_ListVoicesResponse.Size(m)
}
func (m *ListVoicesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListVoicesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListVoicesResponse proto.InternalMessageInfo

func (m *ListVoicesResponse) GetVoices() []*Voice {
	if m != nil {
		return m.Voices
	}
	return nil
}

// Description of a Luna Voice
type Voice struct {
	// Unique identifier of the voice.  This identifier is used to choose the
	// voice during a synthesis request, and is specified in the
	// `SynthesizerConfig` message.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Name of the voice.  This is a concise name describing the voice, and maybe
	// presented to the end-user, for example, to help which voice to choose for
	// their TTS task.
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Voice) Reset()         { *m = Voice{} }
func (m *Voice) String() string { return proto.CompactTextString(m) }
func (*Voice) ProtoMessage()    {}
func (*Voice) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ac2cc9edf97f76d, []int{6}
}

func (m *Voice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Voice.Unmarshal(m, b)
}
func (m *Voice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Voice.Marshal(b, m, deterministic)
}
func (m *Voice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Voice.Merge(m, src)
}
func (m *Voice) XXX_Size() int {
	return xxx_messageInfo_Voice.Size(m)
}
func (m *Voice) XXX_DiscardUnknown() {
	xxx_messageInfo_Voice.DiscardUnknown(m)
}

var xxx_messageInfo_Voice proto.InternalMessageInfo

func (m *Voice) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Voice) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The message returned to the client by the `Synthesize` and
// `SynthesizeStream` methods.
type SynthesizeResponse struct {
	// Audio samples of the entire generated speech, in the 32-bit float encoding,
	// single channel, sampled at 48KHz.
	Samples              []float32 `protobuf:"fixed32,1,rep,packed,name=samples,proto3" json:"samples,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SynthesizeResponse) Reset()         { *m = SynthesizeResponse{} }
func (m *SynthesizeResponse) String() string { return proto.CompactTextString(m) }
func (*SynthesizeResponse) ProtoMessage()    {}
func (*SynthesizeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ac2cc9edf97f76d, []int{7}
}

func (m *SynthesizeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SynthesizeResponse.Unmarshal(m, b)
}
func (m *SynthesizeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SynthesizeResponse.Marshal(b, m, deterministic)
}
func (m *SynthesizeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SynthesizeResponse.Merge(m, src)
}
func (m *SynthesizeResponse) XXX_Size() int {
	return xxx_messageInfo_SynthesizeResponse.Size(m)
}
func (m *SynthesizeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SynthesizeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SynthesizeResponse proto.InternalMessageInfo

func (m *SynthesizeResponse) GetSamples() []float32 {
	if m != nil {
		return m.Samples
	}
	return nil
}

func init() {
	proto.RegisterType((*VersionRequest)(nil), "cobaltspeech.luna.VersionRequest")
	proto.RegisterType((*ListVoicesRequest)(nil), "cobaltspeech.luna.ListVoicesRequest")
	proto.RegisterType((*SynthesizeRequest)(nil), "cobaltspeech.luna.SynthesizeRequest")
	proto.RegisterType((*SynthesizerConfig)(nil), "cobaltspeech.luna.SynthesizerConfig")
	proto.RegisterType((*VersionResponse)(nil), "cobaltspeech.luna.VersionResponse")
	proto.RegisterType((*ListVoicesResponse)(nil), "cobaltspeech.luna.ListVoicesResponse")
	proto.RegisterType((*Voice)(nil), "cobaltspeech.luna.Voice")
	proto.RegisterType((*SynthesizeResponse)(nil), "cobaltspeech.luna.SynthesizeResponse")
}

func init() { proto.RegisterFile("luna.proto", fileDescriptor_8ac2cc9edf97f76d) }

var fileDescriptor_8ac2cc9edf97f76d = []byte{
	// 346 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0x41, 0x6b, 0xf2, 0x40,
	0x10, 0x25, 0xf9, 0xfc, 0xa2, 0x8e, 0x60, 0x75, 0x7a, 0x49, 0x3d, 0xd9, 0xa5, 0x05, 0x41, 0x08,
	0x62, 0xaf, 0x3d, 0xb5, 0x50, 0x28, 0x78, 0x28, 0x11, 0x84, 0xf6, 0x52, 0xd6, 0x38, 0xad, 0x0b,
	0xba, 0x9b, 0x66, 0x57, 0x69, 0xfb, 0xaf, 0xfb, 0x0f, 0x4a, 0xd6, 0xd5, 0x58, 0x0c, 0xf6, 0xd2,
	0xdb, 0xce, 0xdb, 0x37, 0xf3, 0xde, 0xdb, 0x49, 0x00, 0x16, 0x2b, 0xc9, 0xa3, 0x34, 0x53, 0x46,
	0x61, 0x3b, 0x51, 0x53, 0xbe, 0x30, 0x3a, 0x25, 0x4a, 0xe6, 0x51, 0x7e, 0xc1, 0x5a, 0xd0, 0x9c,
	0x50, 0xa6, 0x85, 0x92, 0x31, 0xbd, 0xad, 0x48, 0x1b, 0x76, 0x0a, 0xed, 0x91, 0xd0, 0x66, 0xa2,
	0x44, 0x42, 0x7a, 0x0b, 0x12, 0xb4, 0xc7, 0x1f, 0xd2, 0xcc, 0x49, 0x8b, 0x4f, 0x72, 0x20, 0x5e,
	0x43, 0x90, 0x28, 0xf9, 0x22, 0x5e, 0x43, 0xaf, 0xeb, 0xf5, 0x1a, 0xc3, 0x8b, 0xe8, 0x60, 0x7e,
	0x54, 0x74, 0x65, 0xb7, 0x96, 0x1b, 0xbb, 0x1e, 0x44, 0xa8, 0x18, 0x7a, 0x37, 0xa1, 0xdf, 0xf5,
	0x7a, 0xf5, 0xd8, 0x9e, 0x59, 0xb4, 0x2f, 0xe3, 0x1a, 0xf0, 0x0c, 0x6a, 0xeb, 0xdc, 0xcc, 0xb3,
	0x98, 0x59, 0xa1, 0x7a, 0x5c, 0xb5, 0xf5, 0xfd, 0x8c, 0xf5, 0xe1, 0x64, 0xe7, 0x5e, 0xa7, 0x4a,
	0x6a, 0xc2, 0x10, 0xaa, 0xeb, 0x0d, 0xb4, 0x23, 0x6f, 0x4a, 0x76, 0x07, 0xb8, 0x1f, 0xcc, 0xf1,
	0x07, 0x10, 0xd8, 0x69, 0x3a, 0xf4, 0xba, 0xff, 0x7a, 0x8d, 0x61, 0x58, 0x12, 0xc2, 0xb6, 0xc4,
	0x8e, 0xc7, 0xfa, 0xf0, 0xdf, 0x02, 0xd8, 0x04, 0x7f, 0x67, 0xc9, 0x17, 0xb3, 0x3c, 0x91, 0xe4,
	0x4b, 0xda, 0x26, 0xca, 0xcf, 0x2c, 0x02, 0xdc, 0x7f, 0xb8, 0xc2, 0xa4, 0xe6, 0xcb, 0x74, 0xe1,
	0x54, 0xfd, 0x78, 0x5b, 0x0e, 0xbf, 0x7c, 0xa8, 0x8c, 0x56, 0x92, 0xe3, 0x03, 0x54, 0x5d, 0x34,
	0x3c, 0x2f, 0xb3, 0xf4, 0x63, 0x69, 0x1d, 0x76, 0x8c, 0xe2, 0x44, 0x1f, 0x01, 0x8a, 0xfc, 0x58,
	0xb6, 0xac, 0x83, 0xbd, 0x77, 0x2e, 0x7f, 0x61, 0x15, 0xa3, 0x8b, 0x94, 0x78, 0xfc, 0x3b, 0x38,
	0x36, 0xba, 0xe4, 0xa9, 0x38, 0xb4, 0x0a, 0x74, 0x6c, 0x32, 0xe2, 0xcb, 0x3f, 0x15, 0x18, 0x78,
	0x37, 0xb5, 0xa7, 0x20, 0xbf, 0x4c, 0xa7, 0xd3, 0xc0, 0xfe, 0x27, 0x57, 0xdf, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x3c, 0xd9, 0x48, 0x9c, 0x35, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LunaClient is the client API for Luna service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LunaClient interface {
	// Queries the Version of the Server.
	Version(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error)
	// Retrieves a list of available text-to-speech voices.
	ListVoices(ctx context.Context, in *ListVoicesRequest, opts ...grpc.CallOption) (*ListVoicesResponse, error)
	// Performs synchronous text-to-speech generation.
	Synthesize(ctx context.Context, in *SynthesizeRequest, opts ...grpc.CallOption) (*SynthesizeResponse, error)
	// Performs streaming text-to-speech generation, where the synthesized
	// speech is streamed to the client as it is being generated.
	SynthesizeStream(ctx context.Context, in *SynthesizeRequest, opts ...grpc.CallOption) (Luna_SynthesizeStreamClient, error)
}

type lunaClient struct {
	cc *grpc.ClientConn
}

func NewLunaClient(cc *grpc.ClientConn) LunaClient {
	return &lunaClient{cc}
}

func (c *lunaClient) Version(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error) {
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, "/cobaltspeech.luna.Luna/Version", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lunaClient) ListVoices(ctx context.Context, in *ListVoicesRequest, opts ...grpc.CallOption) (*ListVoicesResponse, error) {
	out := new(ListVoicesResponse)
	err := c.cc.Invoke(ctx, "/cobaltspeech.luna.Luna/ListVoices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lunaClient) Synthesize(ctx context.Context, in *SynthesizeRequest, opts ...grpc.CallOption) (*SynthesizeResponse, error) {
	out := new(SynthesizeResponse)
	err := c.cc.Invoke(ctx, "/cobaltspeech.luna.Luna/Synthesize", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lunaClient) SynthesizeStream(ctx context.Context, in *SynthesizeRequest, opts ...grpc.CallOption) (Luna_SynthesizeStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Luna_serviceDesc.Streams[0], "/cobaltspeech.luna.Luna/SynthesizeStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &lunaSynthesizeStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Luna_SynthesizeStreamClient interface {
	Recv() (*SynthesizeResponse, error)
	grpc.ClientStream
}

type lunaSynthesizeStreamClient struct {
	grpc.ClientStream
}

func (x *lunaSynthesizeStreamClient) Recv() (*SynthesizeResponse, error) {
	m := new(SynthesizeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// LunaServer is the server API for Luna service.
type LunaServer interface {
	// Queries the Version of the Server.
	Version(context.Context, *VersionRequest) (*VersionResponse, error)
	// Retrieves a list of available text-to-speech voices.
	ListVoices(context.Context, *ListVoicesRequest) (*ListVoicesResponse, error)
	// Performs synchronous text-to-speech generation.
	Synthesize(context.Context, *SynthesizeRequest) (*SynthesizeResponse, error)
	// Performs streaming text-to-speech generation, where the synthesized
	// speech is streamed to the client as it is being generated.
	SynthesizeStream(*SynthesizeRequest, Luna_SynthesizeStreamServer) error
}

// UnimplementedLunaServer can be embedded to have forward compatible implementations.
type UnimplementedLunaServer struct {
}

func (*UnimplementedLunaServer) Version(ctx context.Context, req *VersionRequest) (*VersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Version not implemented")
}
func (*UnimplementedLunaServer) ListVoices(ctx context.Context, req *ListVoicesRequest) (*ListVoicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListVoices not implemented")
}
func (*UnimplementedLunaServer) Synthesize(ctx context.Context, req *SynthesizeRequest) (*SynthesizeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Synthesize not implemented")
}
func (*UnimplementedLunaServer) SynthesizeStream(req *SynthesizeRequest, srv Luna_SynthesizeStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method SynthesizeStream not implemented")
}

func RegisterLunaServer(s *grpc.Server, srv LunaServer) {
	s.RegisterService(&_Luna_serviceDesc, srv)
}

func _Luna_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LunaServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cobaltspeech.luna.Luna/Version",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LunaServer).Version(ctx, req.(*VersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Luna_ListVoices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVoicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LunaServer).ListVoices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cobaltspeech.luna.Luna/ListVoices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LunaServer).ListVoices(ctx, req.(*ListVoicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Luna_Synthesize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SynthesizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LunaServer).Synthesize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cobaltspeech.luna.Luna/Synthesize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LunaServer).Synthesize(ctx, req.(*SynthesizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Luna_SynthesizeStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SynthesizeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LunaServer).SynthesizeStream(m, &lunaSynthesizeStreamServer{stream})
}

type Luna_SynthesizeStreamServer interface {
	Send(*SynthesizeResponse) error
	grpc.ServerStream
}

type lunaSynthesizeStreamServer struct {
	grpc.ServerStream
}

func (x *lunaSynthesizeStreamServer) Send(m *SynthesizeResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _Luna_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cobaltspeech.luna.Luna",
	HandlerType: (*LunaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Version",
			Handler:    _Luna_Version_Handler,
		},
		{
			MethodName: "ListVoices",
			Handler:    _Luna_ListVoices_Handler,
		},
		{
			MethodName: "Synthesize",
			Handler:    _Luna_Synthesize_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SynthesizeStream",
			Handler:       _Luna_SynthesizeStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "luna.proto",
}
