// Code generated by protoc-gen-go. DO NOT EDIT.
// source: luna.proto

package lunapb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The top-level message sent by the client for the `Version` method.
type VersionRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionRequest) Reset()         { *m = VersionRequest{} }
func (m *VersionRequest) String() string { return proto.CompactTextString(m) }
func (*VersionRequest) ProtoMessage()    {}
func (*VersionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_luna_82ba9c048844d95d, []int{0}
}
func (m *VersionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionRequest.Unmarshal(m, b)
}
func (m *VersionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionRequest.Marshal(b, m, deterministic)
}
func (dst *VersionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionRequest.Merge(dst, src)
}
func (m *VersionRequest) XXX_Size() int {
	return xxx_messageInfo_VersionRequest.Size(m)
}
func (m *VersionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VersionRequest proto.InternalMessageInfo

// The top-level message sent by the client for the `ListVoices` method.
type ListVoicesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListVoicesRequest) Reset()         { *m = ListVoicesRequest{} }
func (m *ListVoicesRequest) String() string { return proto.CompactTextString(m) }
func (*ListVoicesRequest) ProtoMessage()    {}
func (*ListVoicesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_luna_82ba9c048844d95d, []int{1}
}
func (m *ListVoicesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListVoicesRequest.Unmarshal(m, b)
}
func (m *ListVoicesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListVoicesRequest.Marshal(b, m, deterministic)
}
func (dst *ListVoicesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListVoicesRequest.Merge(dst, src)
}
func (m *ListVoicesRequest) XXX_Size() int {
	return xxx_messageInfo_ListVoicesRequest.Size(m)
}
func (m *ListVoicesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListVoicesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListVoicesRequest proto.InternalMessageInfo

// The top-level message sent by the client for the `Synthesize` method.
type SynthesizeRequest struct {
	// Provides configuration for the text-to-speech engine.
	Config *SynthesizerConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	// The text to generate speech for.
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SynthesizeRequest) Reset()         { *m = SynthesizeRequest{} }
func (m *SynthesizeRequest) String() string { return proto.CompactTextString(m) }
func (*SynthesizeRequest) ProtoMessage()    {}
func (*SynthesizeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_luna_82ba9c048844d95d, []int{2}
}
func (m *SynthesizeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SynthesizeRequest.Unmarshal(m, b)
}
func (m *SynthesizeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SynthesizeRequest.Marshal(b, m, deterministic)
}
func (dst *SynthesizeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SynthesizeRequest.Merge(dst, src)
}
func (m *SynthesizeRequest) XXX_Size() int {
	return xxx_messageInfo_SynthesizeRequest.Size(m)
}
func (m *SynthesizeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SynthesizeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SynthesizeRequest proto.InternalMessageInfo

func (m *SynthesizeRequest) GetConfig() *SynthesizerConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *SynthesizeRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

// Configuration for setting up the text-to-speech engine.
type SynthesizerConfig struct {
	VoiceId              string   `protobuf:"bytes,1,opt,name=voice_id,json=voiceId,proto3" json:"voice_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SynthesizerConfig) Reset()         { *m = SynthesizerConfig{} }
func (m *SynthesizerConfig) String() string { return proto.CompactTextString(m) }
func (*SynthesizerConfig) ProtoMessage()    {}
func (*SynthesizerConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_luna_82ba9c048844d95d, []int{3}
}
func (m *SynthesizerConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SynthesizerConfig.Unmarshal(m, b)
}
func (m *SynthesizerConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SynthesizerConfig.Marshal(b, m, deterministic)
}
func (dst *SynthesizerConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SynthesizerConfig.Merge(dst, src)
}
func (m *SynthesizerConfig) XXX_Size() int {
	return xxx_messageInfo_SynthesizerConfig.Size(m)
}
func (m *SynthesizerConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_SynthesizerConfig.DiscardUnknown(m)
}

var xxx_messageInfo_SynthesizerConfig proto.InternalMessageInfo

func (m *SynthesizerConfig) GetVoiceId() string {
	if m != nil {
		return m.VoiceId
	}
	return ""
}

// The message sent by the server for the `Version` method.
type VersionResponse struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionResponse) Reset()         { *m = VersionResponse{} }
func (m *VersionResponse) String() string { return proto.CompactTextString(m) }
func (*VersionResponse) ProtoMessage()    {}
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_luna_82ba9c048844d95d, []int{4}
}
func (m *VersionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionResponse.Unmarshal(m, b)
}
func (m *VersionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionResponse.Marshal(b, m, deterministic)
}
func (dst *VersionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionResponse.Merge(dst, src)
}
func (m *VersionResponse) XXX_Size() int {
	return xxx_messageInfo_VersionResponse.Size(m)
}
func (m *VersionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VersionResponse proto.InternalMessageInfo

func (m *VersionResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

// The message sent by the server for the `ListVoices` method.
type ListVoicesResponse struct {
	// List of voices available for use that match the request.
	Voices               []*Voice `protobuf:"bytes,1,rep,name=voices,proto3" json:"voices,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListVoicesResponse) Reset()         { *m = ListVoicesResponse{} }
func (m *ListVoicesResponse) String() string { return proto.CompactTextString(m) }
func (*ListVoicesResponse) ProtoMessage()    {}
func (*ListVoicesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_luna_82ba9c048844d95d, []int{5}
}
func (m *ListVoicesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListVoicesResponse.Unmarshal(m, b)
}
func (m *ListVoicesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListVoicesResponse.Marshal(b, m, deterministic)
}
func (dst *ListVoicesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListVoicesResponse.Merge(dst, src)
}
func (m *ListVoicesResponse) XXX_Size() int {
	return xxx_messageInfo_ListVoicesResponse.Size(m)
}
func (m *ListVoicesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListVoicesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListVoicesResponse proto.InternalMessageInfo

func (m *ListVoicesResponse) GetVoices() []*Voice {
	if m != nil {
		return m.Voices
	}
	return nil
}

// Description of a Luna Voice
type Voice struct {
	// Unique identifier of the voice.  This identifier is used to choose the
	// voice during a synthesis request, and is specified in the
	// `SynthesizerConfig` message.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Name of the voice.  This is a concise name describing the voice, and maybe
	// presented to the end-user, for example, to help which voice to choose for
	// their TTS task.
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Voice) Reset()         { *m = Voice{} }
func (m *Voice) String() string { return proto.CompactTextString(m) }
func (*Voice) ProtoMessage()    {}
func (*Voice) Descriptor() ([]byte, []int) {
	return fileDescriptor_luna_82ba9c048844d95d, []int{6}
}
func (m *Voice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Voice.Unmarshal(m, b)
}
func (m *Voice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Voice.Marshal(b, m, deterministic)
}
func (dst *Voice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Voice.Merge(dst, src)
}
func (m *Voice) XXX_Size() int {
	return xxx_messageInfo_Voice.Size(m)
}
func (m *Voice) XXX_DiscardUnknown() {
	xxx_messageInfo_Voice.DiscardUnknown(m)
}

var xxx_messageInfo_Voice proto.InternalMessageInfo

func (m *Voice) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Voice) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The message returned to the client by the `Synthesize` method.
type SynthesizeResponse struct {
	// Audio samples of the entire generated speech, in the 32-bit float encoding, single channel, sampled at 48KHz.
	Samples              []float32 `protobuf:"fixed32,1,rep,packed,name=samples,proto3" json:"samples,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SynthesizeResponse) Reset()         { *m = SynthesizeResponse{} }
func (m *SynthesizeResponse) String() string { return proto.CompactTextString(m) }
func (*SynthesizeResponse) ProtoMessage()    {}
func (*SynthesizeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_luna_82ba9c048844d95d, []int{7}
}
func (m *SynthesizeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SynthesizeResponse.Unmarshal(m, b)
}
func (m *SynthesizeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SynthesizeResponse.Marshal(b, m, deterministic)
}
func (dst *SynthesizeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SynthesizeResponse.Merge(dst, src)
}
func (m *SynthesizeResponse) XXX_Size() int {
	return xxx_messageInfo_SynthesizeResponse.Size(m)
}
func (m *SynthesizeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SynthesizeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SynthesizeResponse proto.InternalMessageInfo

func (m *SynthesizeResponse) GetSamples() []float32 {
	if m != nil {
		return m.Samples
	}
	return nil
}

func init() {
	proto.RegisterType((*VersionRequest)(nil), "cobaltspeech.luna.VersionRequest")
	proto.RegisterType((*ListVoicesRequest)(nil), "cobaltspeech.luna.ListVoicesRequest")
	proto.RegisterType((*SynthesizeRequest)(nil), "cobaltspeech.luna.SynthesizeRequest")
	proto.RegisterType((*SynthesizerConfig)(nil), "cobaltspeech.luna.SynthesizerConfig")
	proto.RegisterType((*VersionResponse)(nil), "cobaltspeech.luna.VersionResponse")
	proto.RegisterType((*ListVoicesResponse)(nil), "cobaltspeech.luna.ListVoicesResponse")
	proto.RegisterType((*Voice)(nil), "cobaltspeech.luna.Voice")
	proto.RegisterType((*SynthesizeResponse)(nil), "cobaltspeech.luna.SynthesizeResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LunaClient is the client API for Luna service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LunaClient interface {
	// Queries the Version of the Server
	Version(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error)
	// Retrieves a list of available text-to-speech voices
	ListVoices(ctx context.Context, in *ListVoicesRequest, opts ...grpc.CallOption) (*ListVoicesResponse, error)
	// Performs synchronous text-to-speech generation.
	Synthesize(ctx context.Context, in *SynthesizeRequest, opts ...grpc.CallOption) (*SynthesizeResponse, error)
}

type lunaClient struct {
	cc *grpc.ClientConn
}

func NewLunaClient(cc *grpc.ClientConn) LunaClient {
	return &lunaClient{cc}
}

func (c *lunaClient) Version(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error) {
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, "/cobaltspeech.luna.Luna/Version", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lunaClient) ListVoices(ctx context.Context, in *ListVoicesRequest, opts ...grpc.CallOption) (*ListVoicesResponse, error) {
	out := new(ListVoicesResponse)
	err := c.cc.Invoke(ctx, "/cobaltspeech.luna.Luna/ListVoices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lunaClient) Synthesize(ctx context.Context, in *SynthesizeRequest, opts ...grpc.CallOption) (*SynthesizeResponse, error) {
	out := new(SynthesizeResponse)
	err := c.cc.Invoke(ctx, "/cobaltspeech.luna.Luna/Synthesize", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LunaServer is the server API for Luna service.
type LunaServer interface {
	// Queries the Version of the Server
	Version(context.Context, *VersionRequest) (*VersionResponse, error)
	// Retrieves a list of available text-to-speech voices
	ListVoices(context.Context, *ListVoicesRequest) (*ListVoicesResponse, error)
	// Performs synchronous text-to-speech generation.
	Synthesize(context.Context, *SynthesizeRequest) (*SynthesizeResponse, error)
}

func RegisterLunaServer(s *grpc.Server, srv LunaServer) {
	s.RegisterService(&_Luna_serviceDesc, srv)
}

func _Luna_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LunaServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cobaltspeech.luna.Luna/Version",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LunaServer).Version(ctx, req.(*VersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Luna_ListVoices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVoicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LunaServer).ListVoices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cobaltspeech.luna.Luna/ListVoices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LunaServer).ListVoices(ctx, req.(*ListVoicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Luna_Synthesize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SynthesizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LunaServer).Synthesize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cobaltspeech.luna.Luna/Synthesize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LunaServer).Synthesize(ctx, req.(*SynthesizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Luna_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cobaltspeech.luna.Luna",
	HandlerType: (*LunaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Version",
			Handler:    _Luna_Version_Handler,
		},
		{
			MethodName: "ListVoices",
			Handler:    _Luna_ListVoices_Handler,
		},
		{
			MethodName: "Synthesize",
			Handler:    _Luna_Synthesize_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "luna.proto",
}

func init() { proto.RegisterFile("luna.proto", fileDescriptor_luna_82ba9c048844d95d) }

var fileDescriptor_luna_82ba9c048844d95d = []byte{
	// 331 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x4d, 0x4b, 0x33, 0x31,
	0x10, 0x66, 0xf7, 0xed, 0xbb, 0x6d, 0xa7, 0x50, 0xed, 0x78, 0x59, 0x7b, 0xaa, 0x41, 0xa1, 0x50,
	0x08, 0x52, 0xaf, 0x9e, 0x14, 0x04, 0xa1, 0x07, 0x89, 0x50, 0xd0, 0x8b, 0x6c, 0xb7, 0xa3, 0x0d,
	0xb4, 0xc9, 0xda, 0xa4, 0x45, 0xfd, 0x11, 0xfe, 0x66, 0xd9, 0x34, 0xed, 0x56, 0xba, 0xac, 0xb7,
	0xcc, 0xe4, 0x99, 0xe7, 0x23, 0x13, 0x80, 0xf9, 0x4a, 0x25, 0x3c, 0x5b, 0x6a, 0xab, 0xb1, 0x93,
	0xea, 0x49, 0x32, 0xb7, 0x26, 0x23, 0x4a, 0x67, 0x3c, 0xbf, 0x60, 0xc7, 0xd0, 0x1e, 0xd3, 0xd2,
	0x48, 0xad, 0x04, 0xbd, 0xaf, 0xc8, 0x58, 0x76, 0x02, 0x9d, 0x91, 0x34, 0x76, 0xac, 0x65, 0x4a,
	0x66, 0xdb, 0x24, 0xe8, 0x3c, 0x7e, 0x2a, 0x3b, 0x23, 0x23, 0xbf, 0xc8, 0x37, 0xf1, 0x1a, 0xa2,
	0x54, 0xab, 0x57, 0xf9, 0x16, 0x07, 0xbd, 0xa0, 0xdf, 0x1a, 0x9e, 0xf3, 0x03, 0x7e, 0x5e, 0x4c,
	0x2d, 0x6f, 0x1d, 0x56, 0xf8, 0x19, 0x44, 0xa8, 0x59, 0xfa, 0xb0, 0x71, 0xd8, 0x0b, 0xfa, 0x4d,
	0xe1, 0xce, 0x8c, 0xef, 0xcb, 0xf8, 0x01, 0x3c, 0x85, 0xc6, 0x3a, 0x37, 0xf3, 0x22, 0xa7, 0x4e,
	0xa8, 0x29, 0xea, 0xae, 0xbe, 0x9f, 0xb2, 0x01, 0x1c, 0xed, 0xdc, 0x9b, 0x4c, 0x2b, 0x43, 0x18,
	0x43, 0x7d, 0xbd, 0x69, 0xed, 0xc0, 0x9b, 0x92, 0xdd, 0x01, 0xee, 0x07, 0xf3, 0xf8, 0x4b, 0x88,
	0x1c, 0x9b, 0x89, 0x83, 0xde, 0xbf, 0x7e, 0x6b, 0x18, 0x97, 0x84, 0x70, 0x23, 0xc2, 0xe3, 0xd8,
	0x00, 0xfe, 0xbb, 0x06, 0xb6, 0x21, 0xdc, 0x59, 0x0a, 0xe5, 0x34, 0x4f, 0xa4, 0x92, 0x05, 0x6d,
	0x13, 0xe5, 0x67, 0xc6, 0x01, 0xf7, 0x1f, 0xae, 0x30, 0x69, 0x92, 0x45, 0x36, 0xf7, 0xaa, 0xa1,
	0xd8, 0x96, 0xc3, 0xef, 0x10, 0x6a, 0xa3, 0x95, 0x4a, 0xf0, 0x01, 0xea, 0x3e, 0x1a, 0x9e, 0x95,
	0x59, 0xfa, 0xb5, 0xb4, 0x2e, 0xab, 0x82, 0x78, 0xd1, 0x27, 0x80, 0x22, 0x3f, 0x96, 0x2d, 0xeb,
	0x60, 0xef, 0xdd, 0x8b, 0x3f, 0x50, 0x05, 0x75, 0x91, 0x12, 0xab, 0xff, 0x41, 0x15, 0xf5, 0xe1,
	0x53, 0xdd, 0x34, 0x9e, 0xa3, 0xfc, 0x2a, 0x9b, 0x4c, 0x22, 0xf7, 0x89, 0xaf, 0x7e, 0x02, 0x00,
	0x00, 0xff, 0xff, 0xd7, 0xdb, 0x2c, 0x50, 0xd2, 0x02, 0x00, 0x00,
}
