// Copyright (2019) Cobalt Speech and Language, Inc.

#ifndef LUNA_EXCEPTION_H
#define LUNA_EXCEPTION_H

#include <exception>
#include <string>

#include <grpcpp/grpcpp.h>

//! LunaException represents an error generated by the
//! Luna client.
class LunaException : public std::exception
{
public:
    LunaException(const std::string &msg);
    LunaException(const grpc::Status &status);
    ~LunaException() override;

    const char *what() const noexcept override;

private:
    std::string mMsg;
};

#endif // LUNA_EXCEPTION_H
