# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: luna.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='luna.proto',
  package='cobaltspeech.luna',
  syntax='proto3',
  serialized_options=_b('Z\006lunapb'),
  serialized_pb=_b('\n\nluna.proto\x12\x11\x63obaltspeech.luna\"\x10\n\x0eVersionRequest\"\x13\n\x11ListVoicesRequest\"W\n\x11SynthesizeRequest\x12\x34\n\x06\x63onfig\x18\x01 \x01(\x0b\x32$.cobaltspeech.luna.SynthesizerConfig\x12\x0c\n\x04text\x18\x02 \x01(\t\"%\n\x11SynthesizerConfig\x12\x10\n\x08voice_id\x18\x01 \x01(\t\"\"\n\x0fVersionResponse\x12\x0f\n\x07version\x18\x01 \x01(\t\">\n\x12ListVoicesResponse\x12(\n\x06voices\x18\x01 \x03(\x0b\x32\x18.cobaltspeech.luna.Voice\"!\n\x05Voice\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"%\n\x12SynthesizeResponse\x12\x0f\n\x07samples\x18\x01 \x03(\x02\x32\xf1\x02\n\x04Luna\x12P\n\x07Version\x12!.cobaltspeech.luna.VersionRequest\x1a\".cobaltspeech.luna.VersionResponse\x12Y\n\nListVoices\x12$.cobaltspeech.luna.ListVoicesRequest\x1a%.cobaltspeech.luna.ListVoicesResponse\x12Y\n\nSynthesize\x12$.cobaltspeech.luna.SynthesizeRequest\x1a%.cobaltspeech.luna.SynthesizeResponse\x12\x61\n\x10SynthesizeStream\x12$.cobaltspeech.luna.SynthesizeRequest\x1a%.cobaltspeech.luna.SynthesizeResponse0\x01\x42\x08Z\x06lunapbb\x06proto3')
)




_VERSIONREQUEST = _descriptor.Descriptor(
  name='VersionRequest',
  full_name='cobaltspeech.luna.VersionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=49,
)


_LISTVOICESREQUEST = _descriptor.Descriptor(
  name='ListVoicesRequest',
  full_name='cobaltspeech.luna.ListVoicesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=70,
)


_SYNTHESIZEREQUEST = _descriptor.Descriptor(
  name='SynthesizeRequest',
  full_name='cobaltspeech.luna.SynthesizeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='config', full_name='cobaltspeech.luna.SynthesizeRequest.config', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='cobaltspeech.luna.SynthesizeRequest.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=159,
)


_SYNTHESIZERCONFIG = _descriptor.Descriptor(
  name='SynthesizerConfig',
  full_name='cobaltspeech.luna.SynthesizerConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='voice_id', full_name='cobaltspeech.luna.SynthesizerConfig.voice_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=161,
  serialized_end=198,
)


_VERSIONRESPONSE = _descriptor.Descriptor(
  name='VersionResponse',
  full_name='cobaltspeech.luna.VersionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='cobaltspeech.luna.VersionResponse.version', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=200,
  serialized_end=234,
)


_LISTVOICESRESPONSE = _descriptor.Descriptor(
  name='ListVoicesResponse',
  full_name='cobaltspeech.luna.ListVoicesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='voices', full_name='cobaltspeech.luna.ListVoicesResponse.voices', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=236,
  serialized_end=298,
)


_VOICE = _descriptor.Descriptor(
  name='Voice',
  full_name='cobaltspeech.luna.Voice',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='cobaltspeech.luna.Voice.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='cobaltspeech.luna.Voice.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=300,
  serialized_end=333,
)


_SYNTHESIZERESPONSE = _descriptor.Descriptor(
  name='SynthesizeResponse',
  full_name='cobaltspeech.luna.SynthesizeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='samples', full_name='cobaltspeech.luna.SynthesizeResponse.samples', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=335,
  serialized_end=372,
)

_SYNTHESIZEREQUEST.fields_by_name['config'].message_type = _SYNTHESIZERCONFIG
_LISTVOICESRESPONSE.fields_by_name['voices'].message_type = _VOICE
DESCRIPTOR.message_types_by_name['VersionRequest'] = _VERSIONREQUEST
DESCRIPTOR.message_types_by_name['ListVoicesRequest'] = _LISTVOICESREQUEST
DESCRIPTOR.message_types_by_name['SynthesizeRequest'] = _SYNTHESIZEREQUEST
DESCRIPTOR.message_types_by_name['SynthesizerConfig'] = _SYNTHESIZERCONFIG
DESCRIPTOR.message_types_by_name['VersionResponse'] = _VERSIONRESPONSE
DESCRIPTOR.message_types_by_name['ListVoicesResponse'] = _LISTVOICESRESPONSE
DESCRIPTOR.message_types_by_name['Voice'] = _VOICE
DESCRIPTOR.message_types_by_name['SynthesizeResponse'] = _SYNTHESIZERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VersionRequest = _reflection.GeneratedProtocolMessageType('VersionRequest', (_message.Message,), dict(
  DESCRIPTOR = _VERSIONREQUEST,
  __module__ = 'luna_pb2'
  # @@protoc_insertion_point(class_scope:cobaltspeech.luna.VersionRequest)
  ))
_sym_db.RegisterMessage(VersionRequest)

ListVoicesRequest = _reflection.GeneratedProtocolMessageType('ListVoicesRequest', (_message.Message,), dict(
  DESCRIPTOR = _LISTVOICESREQUEST,
  __module__ = 'luna_pb2'
  # @@protoc_insertion_point(class_scope:cobaltspeech.luna.ListVoicesRequest)
  ))
_sym_db.RegisterMessage(ListVoicesRequest)

SynthesizeRequest = _reflection.GeneratedProtocolMessageType('SynthesizeRequest', (_message.Message,), dict(
  DESCRIPTOR = _SYNTHESIZEREQUEST,
  __module__ = 'luna_pb2'
  # @@protoc_insertion_point(class_scope:cobaltspeech.luna.SynthesizeRequest)
  ))
_sym_db.RegisterMessage(SynthesizeRequest)

SynthesizerConfig = _reflection.GeneratedProtocolMessageType('SynthesizerConfig', (_message.Message,), dict(
  DESCRIPTOR = _SYNTHESIZERCONFIG,
  __module__ = 'luna_pb2'
  # @@protoc_insertion_point(class_scope:cobaltspeech.luna.SynthesizerConfig)
  ))
_sym_db.RegisterMessage(SynthesizerConfig)

VersionResponse = _reflection.GeneratedProtocolMessageType('VersionResponse', (_message.Message,), dict(
  DESCRIPTOR = _VERSIONRESPONSE,
  __module__ = 'luna_pb2'
  # @@protoc_insertion_point(class_scope:cobaltspeech.luna.VersionResponse)
  ))
_sym_db.RegisterMessage(VersionResponse)

ListVoicesResponse = _reflection.GeneratedProtocolMessageType('ListVoicesResponse', (_message.Message,), dict(
  DESCRIPTOR = _LISTVOICESRESPONSE,
  __module__ = 'luna_pb2'
  # @@protoc_insertion_point(class_scope:cobaltspeech.luna.ListVoicesResponse)
  ))
_sym_db.RegisterMessage(ListVoicesResponse)

Voice = _reflection.GeneratedProtocolMessageType('Voice', (_message.Message,), dict(
  DESCRIPTOR = _VOICE,
  __module__ = 'luna_pb2'
  # @@protoc_insertion_point(class_scope:cobaltspeech.luna.Voice)
  ))
_sym_db.RegisterMessage(Voice)

SynthesizeResponse = _reflection.GeneratedProtocolMessageType('SynthesizeResponse', (_message.Message,), dict(
  DESCRIPTOR = _SYNTHESIZERESPONSE,
  __module__ = 'luna_pb2'
  # @@protoc_insertion_point(class_scope:cobaltspeech.luna.SynthesizeResponse)
  ))
_sym_db.RegisterMessage(SynthesizeResponse)


DESCRIPTOR._options = None

_LUNA = _descriptor.ServiceDescriptor(
  name='Luna',
  full_name='cobaltspeech.luna.Luna',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=375,
  serialized_end=744,
  methods=[
  _descriptor.MethodDescriptor(
    name='Version',
    full_name='cobaltspeech.luna.Luna.Version',
    index=0,
    containing_service=None,
    input_type=_VERSIONREQUEST,
    output_type=_VERSIONRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ListVoices',
    full_name='cobaltspeech.luna.Luna.ListVoices',
    index=1,
    containing_service=None,
    input_type=_LISTVOICESREQUEST,
    output_type=_LISTVOICESRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Synthesize',
    full_name='cobaltspeech.luna.Luna.Synthesize',
    index=2,
    containing_service=None,
    input_type=_SYNTHESIZEREQUEST,
    output_type=_SYNTHESIZERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SynthesizeStream',
    full_name='cobaltspeech.luna.Luna.SynthesizeStream',
    index=3,
    containing_service=None,
    input_type=_SYNTHESIZEREQUEST,
    output_type=_SYNTHESIZERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_LUNA)

DESCRIPTOR.services_by_name['Luna'] = _LUNA

# @@protoc_insertion_point(module_scope)
